name: injectable_final
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  get_it: 7.6.7
  injectable: 2.3.2

dev_dependencies:
  flutter_lints: 3.0.1
  injectable_generator: 2.4.1
  build_runner: 2.4.8